import AppKit

/// A snapshot of the pasteboard, normalized for storage.
struct CapturedClipboard {
    struct ExtraFormat {
        let pasteboardType: String
        let text: String?
        let data: Data?
    }

    let type: ClipboardType
    let preview: String
    let plainText: String?
    let imageData: Data? // Always PNG when present.
    let hash: String
    let metadata: [String: String]
    let extraFormats: [ExtraFormat]
}

/// Reads NSPasteboard contents and classifies them into a CapturedClipboard.
enum ClipboardReader {
    static let concealedTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    ]

    static func read(from pasteboard: NSPasteboard) -> CapturedClipboard? {
        let types = pasteboard.types ?? []

        // Password managers and other well-behaved apps mark secrets with
        // these types (nspasteboard.org convention). Never record them.
        if types.contains(where: { concealedTypes.contains($0) }) {
            return nil
        }

        if let captured = readFileURLs(pasteboard) { return captured }
        if let captured = readImage(pasteboard) { return captured }
        if let captured = readText(pasteboard) { return captured }
        return nil
    }

    // MARK: - Files

    private static func readFileURLs(_ pasteboard: NSPasteboard) -> CapturedClipboard? {
        let options: [NSPasteboard.ReadingOptionKey: Any] = [.urlReadingFileURLsOnly: true]
        guard let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: options) as? [URL],
              !urls.isEmpty else {
            return nil
        }

        let paths = urls.map(\.path)
        let names = urls.map(\.lastPathComponent)
        let preview = names.count == 1
            ? names[0]
            : "\(names[0]) and \(names.count - 1) more"

        // Include modification dates so a re-saved file counts as new content.
        var hashInput = paths.joined(separator: "\n")
        for url in urls {
            if let modified = try? FileManager.default
                .attributesOfItem(atPath: url.path)[.modificationDate] as? Date {
                hashInput += "|\(modified.timeIntervalSince1970)"
            }
        }

        return CapturedClipboard(
            type: .file,
            preview: preview,
            plainText: paths.joined(separator: "\n"),
            imageData: nil,
            hash: Hashing.itemHash(type: .file, text: hashInput),
            metadata: ["count": String(urls.count)],
            extraFormats: []
        )
    }

    // MARK: - Images

    private static func readImage(_ pasteboard: NSPasteboard) -> CapturedClipboard? {
        var pngData: Data?

        if let png = pasteboard.data(forType: .png) {
            pngData = png
        } else if let tiff = pasteboard.data(forType: .tiff),
                  let rep = NSBitmapImageRep(data: tiff) {
            pngData = rep.representation(using: .png, properties: [:])
        }

        guard let data = pngData else { return nil }

        // Respect the max image size preference.
        let maxBytes = PreferencesManager.shared.maxImageBytes
        guard data.count <= maxBytes else { return nil }

        var metadata: [String: String] = [:]
        var dimensions = ""
        if let rep = NSBitmapImageRep(data: data) {
            metadata["width"] = String(rep.pixelsWide)
            metadata["height"] = String(rep.pixelsHigh)
            dimensions = " \(rep.pixelsWide)×\(rep.pixelsHigh)"
        }

        return CapturedClipboard(
            type: .image,
            preview: "Image\(dimensions)",
            plainText: nil,
            imageData: data,
            hash: Hashing.itemHash(type: .image, content: data),
            metadata: metadata,
            extraFormats: []
        )
    }

    // MARK: - Text and URLs

    private static func readText(_ pasteboard: NSPasteboard) -> CapturedClipboard? {
        guard let raw = pasteboard.string(forType: .string) else { return nil }
        let text = Hashing.normalize(raw)
        guard !text.isEmpty else { return nil }

        // Respect the max text size preference.
        guard raw.utf8.count <= PreferencesManager.shared.maxTextBytes else { return nil }

        let type: ClipboardType = isURL(text) ? .url : .text
        let preview = String(text.prefix(200))

        // Keep richer representations so paste-back preserves formatting.
        var extras: [CapturedClipboard.ExtraFormat] = []
        if let html = pasteboard.string(forType: .html) {
            extras.append(.init(pasteboardType: NSPasteboard.PasteboardType.html.rawValue,
                                text: html, data: nil))
        }
        if let rtf = pasteboard.data(forType: .rtf) {
            extras.append(.init(pasteboardType: NSPasteboard.PasteboardType.rtf.rawValue,
                                text: nil, data: rtf))
        }

        return CapturedClipboard(
            type: type,
            preview: preview,
            plainText: raw,
            imageData: nil,
            hash: Hashing.itemHash(type: type, text: text),
            metadata: [:],
            extraFormats: extras
        )
    }

    private static func isURL(_ text: String) -> Bool {
        guard !text.contains(where: \.isWhitespace),
              let url = URL(string: text),
              let scheme = url.scheme?.lowercased() else {
            return false
        }
        return ["http", "https", "ftp", "file"].contains(scheme) && url.host != nil
    }
}
